version: 0.2

phases:
  build:
    commands:
      - echo 'deploy start...'
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - cat /root/.kube/config
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl version
      - kubectl get node
      - kubectl get pod
  post_build:
    commands:

