version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.

  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: eks-deploy-user
      - run: kubectl version

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: eks-deploy
      - aws-cli-example:
          context: eks-deploy
